# Auto-generated prompt modules
# DO NOT EDIT THIS FILE MANUALLY

# Import all app modules
from .apps import doctor_gpt
from .apps import meeting_summarizer
from .apps import prompt_demo

# Make apps available at top level
meeting_summarizer = meeting_summarizer
doctor_gpt = doctor_gpt
prompt_demo = prompt_demo
